# version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8002"
