---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: |
          docker compose run --rm app sh -c "flake8"
